name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install
        run: npm install
      - name: Preflight check
        run: |
          echo "Workspace layout:" && ls -lah && echo "\nTree (top-level):" && ls -lah .
          echo "\nCheck required files:" \
          && test -f index.html || (echo "Missing index.html" && exit 1) \
          && test -f vite.config.js || (echo "Missing vite.config.js" && exit 1) \
          && test -f package.json || (echo "Missing package.json" && exit 1) 
          echo "\nCheck src entry:"
          test -f src/main.jsx || (echo "Missing src/main.jsx. Please upload the entire src directory." && exit 1)
          echo "OK: src/main.jsx found"
      - name: Build
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

