name: Deploy to GitHub Pages (web/)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install (root workspaces)
        run: npm install
      - name: Preflight check (web)
        run: |
          echo "Root layout:" && ls -lah
          echo "\nCheck web folder:" && ls -lah web
          test -f web/package.json || (echo "Missing web/package.json" && exit 1)
          test -f web/index.html || (echo "Missing web/index.html" && exit 1)
          test -f web/vite.config.ts || (echo "Missing web/vite.config.ts" && exit 1)
          test -f web/src/main.tsx || (echo "Missing web/src/main.tsx" && exit 1)
      - name: Build web
        working-directory: web
        env:
          VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL }}
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: web/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

